---
prod:
  hosts:
    broker1:
      zookeeper_id: 1
      kafka_id: 1
      ansible_host: 192.168.99.11
      ansible_port: 22
      ansible_user: vagrant
      ansible_ssh_private_key_file: ../kafka/.vagrant/machines/broker1/virtualbox/private_key
      ansible_python_interpreter: /usr/bin/python3

    broker2:
      zookeeper_id: 2
      kafka_id: 2
      ansible_host: 192.168.99.12
      ansible_port: 22
      ansible_user: vagrant
      ansible_ssh_private_key_file: ../kafka/.vagrant/machines/broker2/virtualbox/private_key
      ansible_python_interpreter: /usr/bin/python3

    broker3:
      kafka_id: 3
      zookeeper_id: 3
      ansible_host: 192.168.99.13
      ansible_port: 22
      ansible_user: vagrant
      ansible_ssh_private_key_file: ../kafka/.vagrant/machines/broker3/virtualbox/private_key
      ansible_python_interpreter: /usr/bin/python3

